export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const cursosTypes = {
    MOSTRAR_CURSOS: 'MOSTRAR_CURSOS',
    AGREGAR_EDITAR_CURSOS: 'AGREGAR_EDITAR_CURSOS',
    ELIMINAR_CURSOS: 'ELIMINAR_CURSOS',
    ABRIR_MODAL_CURSOS: 'ABRIR_MODAL_CURSOS',
    CERRAR_MODAL_CURSOS: 'CERRAR_MODAL_CURSOS'
};
//COMPARTIDOS
export const _PENDING = '_PENDING';
export const _REJECTED = '_REJECTED';
export const _FULFILLED = '_FULFILLED';